language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - coverage run --source=pyrouter setup.py test

after_success:
  - coveralls

notifications:
  email: false